services:
  - name: projetofotografo
    type: web
    env: python
    region: oregon
    plan: free
    buildCommand: "./install_packages.sh && pip install --no-cache-dir -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: GOOGLE_CREDENTIALS_BASE64
        sync: false
